blogapp/urls.py
from django.urls import path
from .views import *


app_name = 'blogapp'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
    path('blog/list/', BlogListView.as_view(), name='bloglist'),
    path('blog/<int:pk>/detail/', BlogDetailView.as_view(), name='blogdetail'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blogdelete'),
    path('blog/create/', BlogCreateView.as_view(), name='blogcreate'),



    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blogupdate'),



    path('student/list/', StudentListView.as_view(), name="studentlist"),



]

blogproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, null=True, blank=True)
    image = models.ImageField(upload_to='blogs')
    content = models.TextField()
    author = models.CharField(max_length=100)
    posted_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.posted_date)


class Student(models.Model):
    name = models.CharField(max_length=100)
    grade = models.PositiveIntegerField()
    roll_no = models.PositiveIntegerField()
    image = models.ImageField(upload_to="students")
    fathers_name = models.CharField(max_length=100)
    mobile = models.CharField(max_length=100)

    def __str__(self):
        return self.name

blogapp/forms.py
from django import forms
from .models import *


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'image', 'content', 'author']

blogapp/views.py
from django.views.generic import *
from .forms import *


class HomeView(TemplateView):
    template_name = 'home.html'


class ContactView(TemplateView):
    template_name = 'contact.html'


class AboutView(TemplateView):
    template_name = 'about.html'


class BlogListView(ListView):
    template_name = 'bloglist.html'
    queryset = Blog.objects.all().order_by('-id')
    context_object_name = 'bloglist'


class BlogDetailView(DetailView):
    template_name = 'blogdetail.html'
    model = Blog
    context_object_name = 'blogdetail'


class BlogCreateView(CreateView):
    template_name = 'blogcreate.html'
    form_class = BlogForm
    success_url = '/blog/list/'


class BlogUpdateView(UpdateView):
    template_name = 'blogcreate.html'
    model = Blog
    form_class = BlogForm
    success_url = '/blog/list/'


class BlogDeleteView(DeleteView):
    template_name = 'blogdelete.html'
    model = Blog
    success_url = '/blog/list/'


class StudentListView(ListView):
    template_name = "studentlist.html"
    queryset = Student.objects.all().order_by('-id')
    context_object_name = "all_students"

templates/about.html
{% extends 'base.html' %}


{% block content %}
<h3>This Is About Page</h3>


{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body class="container">
	<a href="{% url 'blogapp:home' %}">Home</a> |
	<a href="{% url 'blogapp:contact' %}">Contact</a> |
	<a href="{% url 'blogapp:about' %}">About</a> |
	<a href="{% url 'blogapp:bloglist' %}">Blogs</a> |
	<a href="{% url 'blogapp:blogcreate' %}">Create New Blog</a>
	<hr>

	{% block content %}
	{% endblock %}

</body>
</html>

templates/blogcreate.html
{% extends 'base.html' %}

{% block content %}
<h4>Blog Create/Update Form</h4><hr>
<div class="row">
	<div class="col-12">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p}}
			<button>Submit</button>
			
		</form>
			
	</div>
</div>

{% endblock %}

templates/blogdelete.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-12">
		<form method="POST" action="/blog/{{object.id}}/delete/">
			{% csrf_token %}
			<h4>Delete this Blog?</h4>
			<button>Delete</button>
			<a href="/blog/list/">Cancel</a>
			
		</form>
			
	</div>
</div>

{% endblock %}

templates/blogdetail.html
{% extends 'base.html' %}

{% block content %}
<h4 class="text-info">{{blogdetail}}</h4>
<div class="row">
	<div class="col-12">
		<h4>Title: {{blogdetail.title}}<small>Posted on: {{blogdetail.posted_date}}</small></h4><hr>
		<a class="btn btn-info" href="/blog/{{blogdetail.id}}/update/">Update this Blog</a>
		<a class="btn btn-danger" href="/blog/{{blogdetail.id}}/delete/">Delete this Blog</a><br>
		<img src="{{blogdetail.image.url}}" width="500" class="img-fluid">
		<p>{{blogdetail.content}}</p>
		<hr>
		<p>Author: {{blogdetail.author}}</p>
	</div>
</div>

{% endblock %}

templates/bloglist.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
	{% for blog in bloglist %}
	<div class="col-4">
		<h4 ><a href="/blog/{{blog.id}}/detail/">{{blog.title}}</a></h4>
		<img src="{{blog.image.url}}" class="img-fluid">
		<p>{{blog.content|truncatewords:'20'}}</p>
		<a href="{% url 'blogapp:blogdetail' blog.id %}">Read More</a>
	</div>

	{% endfor %}
</div>

{% endblock %}

templates/contact.html
{% extends 'base.html' %}


{% block content %}
<h3>Hello this is contact page. </h3>

{% endblock %}

templates/home.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
	<div class="col-8 mx-auto">
		
		<h1 class="text-primary text-center">Welcome to Sarobar Technology</h3>
		<h2 class="text-info text-center">Workshop on Python and Django</h4>

	</div>
</div>

{% endblock %}

templates/studentlist.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h4>Student List</h4><hr>
	{% for student in all_students %}
		<li>{{student.name}}</li>
	{% endfor %}

</body>
</html>